/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CertificateVerification {
  export type CertificateStruct = {
    studentName: string;
    studentId: string;
    degree: string;
    university: string;
    ipfsHash: string;
    issuer: AddressLike;
    timestamp: BigNumberish;
    isValid: boolean;
  };

  export type CertificateStructOutput = [
    studentName: string,
    studentId: string,
    degree: string,
    university: string,
    ipfsHash: string,
    issuer: string,
    timestamp: bigint,
    isValid: boolean
  ] & {
    studentName: string;
    studentId: string;
    degree: string;
    university: string;
    ipfsHash: string;
    issuer: string;
    timestamp: bigint;
    isValid: boolean;
  };
}

export interface CertificateVerificationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeIssuer"
      | "authorizedIssuers"
      | "certificateExists"
      | "certificates"
      | "getCertificateDetails"
      | "getUniversityByIssuer"
      | "isCertificateValid"
      | "revokeCertificate"
      | "storeCertificate"
      | "verifyCertificate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CertificateRevoked"
      | "CertificateStored"
      | "IssuerAuthorized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeIssuer",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedIssuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "certificateExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "certificates",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificateDetails",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUniversityByIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCertificateValid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCertificate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeCertificate",
    values: [BytesLike, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCertificate",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificateExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificateDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUniversityByIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCertificateValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCertificate",
    data: BytesLike
  ): Result;
}

export namespace CertificateRevokedEvent {
  export type InputTuple = [certificateHash: BytesLike];
  export type OutputTuple = [certificateHash: string];
  export interface OutputObject {
    certificateHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateStoredEvent {
  export type InputTuple = [
    certificateHash: BytesLike,
    issuer: AddressLike,
    studentName: string,
    university: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    certificateHash: string,
    issuer: string,
    studentName: string,
    university: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    certificateHash: string;
    issuer: string;
    studentName: string;
    university: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerAuthorizedEvent {
  export type InputTuple = [issuer: AddressLike, university: string];
  export type OutputTuple = [issuer: string, university: string];
  export interface OutputObject {
    issuer: string;
    university: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertificateVerification extends BaseContract {
  connect(runner?: ContractRunner | null): CertificateVerification;
  waitForDeployment(): Promise<this>;

  interface: CertificateVerificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeIssuer: TypedContractMethod<
    [_issuer: AddressLike, _university: string],
    [void],
    "nonpayable"
  >;

  authorizedIssuers: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  certificateExists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  certificates: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, string, string, bigint, boolean] & {
        studentName: string;
        studentId: string;
        degree: string;
        university: string;
        ipfsHash: string;
        issuer: string;
        timestamp: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;

  getCertificateDetails: TypedContractMethod<
    [_certificateHash: BytesLike],
    [
      [string, string, string, string, string, string, bigint, boolean] & {
        studentName: string;
        studentId: string;
        degree: string;
        university: string;
        ipfsHash: string;
        issuer: string;
        timestamp: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;

  getUniversityByIssuer: TypedContractMethod<
    [_issuer: AddressLike],
    [string],
    "view"
  >;

  isCertificateValid: TypedContractMethod<
    [_certificateHash: BytesLike],
    [boolean],
    "view"
  >;

  revokeCertificate: TypedContractMethod<
    [_certificateHash: BytesLike],
    [void],
    "nonpayable"
  >;

  storeCertificate: TypedContractMethod<
    [
      _certificateHash: BytesLike,
      _studentName: string,
      _studentId: string,
      _degree: string,
      _ipfsHash: string
    ],
    [void],
    "nonpayable"
  >;

  verifyCertificate: TypedContractMethod<
    [_certificateHash: BytesLike],
    [CertificateVerification.CertificateStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeIssuer"
  ): TypedContractMethod<
    [_issuer: AddressLike, _university: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedIssuers"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "certificateExists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, string, string, bigint, boolean] & {
        studentName: string;
        studentId: string;
        degree: string;
        university: string;
        ipfsHash: string;
        issuer: string;
        timestamp: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCertificateDetails"
  ): TypedContractMethod<
    [_certificateHash: BytesLike],
    [
      [string, string, string, string, string, string, bigint, boolean] & {
        studentName: string;
        studentId: string;
        degree: string;
        university: string;
        ipfsHash: string;
        issuer: string;
        timestamp: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUniversityByIssuer"
  ): TypedContractMethod<[_issuer: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isCertificateValid"
  ): TypedContractMethod<[_certificateHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "revokeCertificate"
  ): TypedContractMethod<[_certificateHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "storeCertificate"
  ): TypedContractMethod<
    [
      _certificateHash: BytesLike,
      _studentName: string,
      _studentId: string,
      _degree: string,
      _ipfsHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyCertificate"
  ): TypedContractMethod<
    [_certificateHash: BytesLike],
    [CertificateVerification.CertificateStructOutput],
    "view"
  >;

  getEvent(
    key: "CertificateRevoked"
  ): TypedContractEvent<
    CertificateRevokedEvent.InputTuple,
    CertificateRevokedEvent.OutputTuple,
    CertificateRevokedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateStored"
  ): TypedContractEvent<
    CertificateStoredEvent.InputTuple,
    CertificateStoredEvent.OutputTuple,
    CertificateStoredEvent.OutputObject
  >;
  getEvent(
    key: "IssuerAuthorized"
  ): TypedContractEvent<
    IssuerAuthorizedEvent.InputTuple,
    IssuerAuthorizedEvent.OutputTuple,
    IssuerAuthorizedEvent.OutputObject
  >;

  filters: {
    "CertificateRevoked(bytes32)": TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;
    CertificateRevoked: TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;

    "CertificateStored(bytes32,address,string,string,uint256)": TypedContractEvent<
      CertificateStoredEvent.InputTuple,
      CertificateStoredEvent.OutputTuple,
      CertificateStoredEvent.OutputObject
    >;
    CertificateStored: TypedContractEvent<
      CertificateStoredEvent.InputTuple,
      CertificateStoredEvent.OutputTuple,
      CertificateStoredEvent.OutputObject
    >;

    "IssuerAuthorized(address,string)": TypedContractEvent<
      IssuerAuthorizedEvent.InputTuple,
      IssuerAuthorizedEvent.OutputTuple,
      IssuerAuthorizedEvent.OutputObject
    >;
    IssuerAuthorized: TypedContractEvent<
      IssuerAuthorizedEvent.InputTuple,
      IssuerAuthorizedEvent.OutputTuple,
      IssuerAuthorizedEvent.OutputObject
    >;
  };
}
